[package]
name = "nodecontroll-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
axum.workspace = true
nodecontroll-application = { path = "../application" }
nodecontroll-config = { path = "../config" }
nodecontroll-domain = { path = "../domain" }
nodecontroll-identity = { path = "../identity" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tower-http.workspace = true
tracing.workspace = true
utoipa.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
