[package]
name = "nodecontroll-persistence"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nodecontroll-domain = { path = "../domain" }
nodecontroll-secrets = { path = "../secrets" }
sqlx.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
